### PR TITLE
[CSL-2974] Fix select question options images height

### PR DESCRIPTION
**Pull request by HHHindawy**

### CODE REVIEW

**Review by mocca102 — CHANGES_REQUESTED** [review]
Image options looking good. The background image for select questions that we discussed still doesn't fill 100% of the height when the view width gets smaller 

Screenshot 2023-11-07 at 4 05 27 AM

**Comment by HHHindawy** [comment]
> Image options looking good. The background image for select questions that we discussed still doesn't fill 100% of the height when the view width gets smaller

Are you sure you're on the right branch? @mocca102  🤔 

image

**Review by mocca102 — APPROVED** [review]
LGTM! lets get a second review. Just making it a habit of two reviewers for UI changes

**Comment by HHHindawy** [comment]
Yes @esezen, this was intentional as agreed with @mocca102.
We wanted to fix the image ratio to unify how images look in case we get different sized images in a single question.

PS: The `aspect-ratio: 1/1` property was always there but didn't take correct effect as it was placed on the wrong element.

**Pull request merged**
